name: Deploy

on:
  push:
    branches: main
    paths:
      - .github/workflows/deploy.yml
      - wrangler.toml
  workflow_run:
    workflows: Test
    branches: main
    types: completed

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Publish
        uses: cloudflare/wrangler-action@v3.8.0
        env:
          WORKER_ENDPOINT: ${{ secrets.WORKER_ENDPOINT }}
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy
