name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - bun.lockb
      - '**.json'
      - '**.ts'

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-biome.yml@0832d473774c1447617374fce8cf68e75c50dd7f # main
