name: Test

on:
  pull_request:
    types: opened
  push:
    paths:
      - .github/workflows/main.yml
      - biome.json
      - tsconfig.json
      - package.json
      - bun.lockb
      - '**.ts'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@f43de6b5804c7609cb6f13864e2d18a70301469e # main
    with:
      disable-formatter: true
      disable-test: true
      disable-build: true
