name: Test

on:
  pull_request:
    types: opened
  push:
    paths:
      - .github/workflows/main.yml
      - biome.json
      - tsconfig.json
      - package.json
      - bun.lockb
      - '**.ts'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@616389d9e449f2a129b80276e49f084812180f4a # main
    with:
      disable-formatter: true
      disable-test: true
      disable-build: true
